ami_id               = "ami-08e5424edfe926b43"
instance_type        = "t2.micro"
key_name             = 
subnet_id            = 
security_group_id    = 
az                   = "ap-south-1a"
volume_size          = 10
volume_type          = "gp3"
source_file_location = "test.sh"